# Font
font_family TerminessTTF Nerd Font
italic_font auto
bold_italic_font auto
font_size 14.0

# Theme
foreground #ffffff
background #000000

url_color #ff0000

# Cursor
cursor #ffffff

term xterm-256color
background_opacity 0.70

color0  #88ff00
color8  #e10023
color1  #ff0e0e
color9  #6a0023

color2  #fa00e5
color10 #c30043

color3  #ff0000
color11 #68f509

color4  #e7e3e3
color12 #000000

color5  #4c00ff
color13 #ffffff

color6  #bb0056
color14 #5d0002

color7  #ff0000
color15 #ff0000


# MAPPED KEYS
map ctrl+v paste_from_clipboard
map ctrl+c copy_to_clipboard
map ctrl+q quit
map ctrl+x send_text all \x03
