#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:


# exec-once = nm-applet &



exec-once = swww-daemon && sleep 0.5 && [ -f ~/.cache/swww/last_wallpaper ] && xargs swww img < ~/.cache/swww/last_wallpaper
exec-once = sleep 3 && quickshell -c ~/.config/quickshell
exec-once = source ~/.config/hypr/hyprland.env
#apps

#exec-once = sleep 2 && hyprctl dispatch movetoworkspace 5,title:Spotify
exec-once = [workspace 1 silent] kitty -e rmpc
exec-once = [workspace 3 silent] steam


# GTK theme 
export GTK3_RC_FILES="$HOME/.config/hyprland/gtk-3.0/settings.ini"
export GTK2_RC_FILES="$HOME/.config/hyprland/gtk-2.0/gtkrc"  


#notification deamon-dunst
exec-once = dunst

exec-once = python3 /home/adi/steam-presence/main.py
#wallpaper switcher
exec-once = matuwall --daemon

#lockscreen
exec-once = hyprlock
exec-once = ibus-daemon -drx