music_directory     "/home/adi/Music/Songs"
playlist_directory  "~/.config/mpd/playlists"
db_file             "~/.local/share/mpd/database"
state_file          "~/.local/share/mpd/state"

auto_update         "yes"
restore_paused      "yes"

audio_output {
    type "pipewire"
    name "PipeWire"
}

audio_output {
    type   "fifo"
    name   "Visualizer feed"
    path   "/tmp/mpd.fifo"
    format "44100:16:2"
}